[tool.poetry]
name = "mimesis"
version = "7.0.0"
description = "Mimesis: Fake Data Generator."
authors = ["Isaak Uchakaev <likid.geimfari@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/lk-geimfari/mimesis"
repository = "https://github.com/lk-geimfari/mimesis"
documentation = "https://mimesis.name"
keywords = [
    "data",
    "datascince",
    "database",
    "dummy",
    "fake",
    "faker",
    "fixtures",
    "generate",
    "mimesis",
    "mock",
    "populate",
    "testing"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Topic :: Software Development",
    "Topic :: Software Development :: Testing",
    "License :: OSI Approved :: MIT License",
]
exclude = [
    "mimesis/data/locale_template",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
codecov = "^2.1"
pytest = "^7.1"
pytest-isort = "^3.0.0"
pytest-cov = "^3.0"
pytest-mock = "^3.10"
requests = "^2.28"
mypy = "^0.960"
colorama = "^0.4.5"
pygments = "^2.13"
pytest-randomly = "^3.12"
check-manifest = "^0.48"
readme-renderer = "^36.0"
pytz = "^2022.5"
black = "^22.10.0"
autoflake = "^1.7"
types-pytz = "^2022.4.0"
taskipy = "^1.10.1"
validators = "^0.20.0"
pytest-repeat = "^0.9.1"
memory-profiler = "^0.60.0"
Sphinx = "^5.1.1"
sphinx-copybutton = "^0.5.0"
sphinx-autodoc-typehints = "^1.19.2"

[tool.pytest.ini_options]
addopts = "--isort"
testpaths = [
    "mimesis",
    "tests",
    "minifier.py",
]

[tool.mypy]
files = ["mimesis", "minifier.py"]
strict_optional = true
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
warn_no_return = false
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_return_any = true
strict_equality = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
default_section = "FIRSTPARTY"

[tool.taskipy.tasks]
minify = "python minifier.py"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

